### ISSUE TITLE
test code

### ISSUE THREAD

**Issue by zw-92** [meyiao/xfeatc#1]
Hello, have you tested the code? I found many errors, such as why the input is converted to a grayscale image, why the input is not resized to a suitable size, and why the input ky and descriptor are 0. I look forward to your reply.

**Comment by meyiao** [comment]
Yes I have tested the code. You can simply run the DetectDemo or MatchDemo to check this. 
1. The input is converted to grayscale because I set the input to be [1, 1, 640, 640] when exporting the onnx model. If you want to use BGR image, you can export your own onnx model , and set the input to be [1, 3, 640, 640].
2. "Suitable size" is 640x640 for my demo, if you want to support other sizes, you need to export your own onnx model using the python code in README.md.
3. "why the input ky and descriptor are 0", sorry I don't know what does that mean

**Comment by zw-92** [comment]
Sorry to bother you, I cropped the input to (640, 640) and grayscale to fit your onnx model. Then I encountered an error when executing auto outputTensors = ortSession_->Run(Ort::RunOptions{nullptr}, inputNames_.data(),inputTensors.data(), 1, outputNames_.data(), outputNames_.size());: reading image...terminate called after throwing an instance of 'Ort::Exception'
what(): input name cannot be empty
Aborted (core dumped)
My onnxruntimes version is 1.18, I guess this is an onnx problem, do you have any clues?

**Comment by zw-92** [comment]
What does the following code mean when doing // bilinear interpolation to get the descriptors? Do I need to modify the parameters when the input size changes?
float x = (pt.pt.x / 639.f) * 80 - 0.5f;
float y = (pt.pt.y / 639.f) * 80 - 0.5f;
Looking forward to your reply！

**Comment by meyiao** [comment]
Please refer to https://github.com/verlab/accelerated_features/blob/main/modules/interpolator.py, the interpolation code is:
```python
  grid = self.normgrid(pos, H, W).unsqueeze(-2).to(x.dtype)
  x = F.grid_sample(x, grid, mode = self.mode , align_corners = False)
```
* the normgrid function is used to normalize the point coordinates to [-1, 1]
    x_normalized = 2 * ptX / (width - 1) - 1; 
    y_normalized = 2 * ptY / (height -1) - 1;

* the grid sample is used to interpolate the descriptors, given a normalized point (x_normalized, y_normalized), its location in the descriptor image is:
   x_interp = (x_normalized + 1) / 2 * desc_img_width - 0.5 = ptX / (width - 1) * desc_img_width - 0.5;
   y_interp = (y_normalized + 1) / 2 * desc_img_height - 0.5 = ptY / (height - 1) * desc_img_height - 0.5;

In the code, widht = height = 640, desc_img_widht=desc_img_height=80.

I should remove those magic numbers, thanks a lot!
